[build]
  functions = "netlify/functions"
  command = "npm run build" # or whatever build command you use
  publish = "public" # specify the directory to publish, if applicable

[[redirects]]
  from = "/*"
  to = "/index.js"
  status = 200