[build]
  command = "npm start"  # or "node index.js" if you directly run your server
  publish = "public"    # Usually used for static files; adjust if needed

[build.environment]
  NODE_VERSION = "16.11.0" 